{% set version = "1.16.3" %}

package:
  name: krb5
  version: {{ version }}

source:
  url: https://github.com/krb5/krb5/archive/krb5-{{ version }}-final.tar.gz
  sha256: abc88d8f69f135ccca4c28a7ebe10f4ee52a06a453e612e98f61a4a037e13d2b
  patches:
    - eafnosupport.patch  # [win and vc<14]
    - jsoneoverflow.patch  # [win and vc<14]
    - afxres.patch  # [win and vc<14]
    - lshutil.patch  # [win and vc<14]

build:
  number: 1002
  run_exports:
    # stable within minor revisions: https://abi-laboratory.pro/tracker/timeline/krb5/
    - {{ pin_subpackage('krb5', max_pin='x.x') }}
  missing_dso_whitelist:          # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison  # [not win]
    - autoconf  # [not win]
    - posix  # [win]
    - perl  5.20.*   # [win]
    - pkg-config  # [unix]
    - make   # [unix]
    - python 2.7  # [unix and not aarch64]
    - python 3.7  # [aarch64]
  host:
    - msinttypes  # [win and vc<14]
    - libedit  # [unix]
    - openssl
    - tk
  run:
    - {{ pin_compatible('libedit') }}  # [unix]
    - openssl
    - tk
    - python 2.7.*  # [win and vc == 9]

test:
  commands:
    - conda inspect linkages -p $PREFIX krb5  # [not win]
    - conda inspect objects -p $PREFIX krb5  # [osx]

about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: 'A network authentication protocol.'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - mingwandroid
    - mariusvniekerk
